tables:
  - name: "stocking-ul"
    rows:
      - type: "AvailableStock"
      - type: "DesiredStock"
      - class: "AvailableQuantity"
      - class: "DesiredQuantity"
      - class: "MissingQuantity"
      - enum: "Batch"
      - enum: "QualityAssuredBatch"
      - class: "BatchID"
      - class: "LabelledProduct"
  - name: "stocking-incoming"
    rows:
      - case: "ProductStocked"
  - name: "stocking-outgoing"
    rows:
      - case: "BatchReadyForQualityAssurance"
      - case: "ProductRemovedFromStock"
      - case: "NewBatch"
  - name: "milk-planning-ul"
    termName: "Term"
    definitionName: "Definition"
    rows:
      - class: "ProcessedMilk"
      - class: "QuintalsOfMilk"
      - class: "Yield"
      - type: "RecipeBook"
      - type: "Stock"
      - class: "StockedQuantity"
      - class: "Quantity"
      - class: "RequestedProduct"

  - name: "milk-planning-incoming"
    termName: "Event"
    definitionName: "Description"
    rows:
      - case: "IncomingEvent.ReceivedOrder"

  - name: "milk-planning-outgoing"
    termName: "Event"
    definitionName: "Description"
    rows:
      - case: "OutgoingEvent.OrderMilk"

ignored: []
