tables:
  - name: "stocking-ul"
    rows:
      - class: "stocking.AvailableStock"
      - class: "stocking.DesiredStock"
      - class: "stocking.AvailableQuantity"
      - class: "stocking.DesiredQuantity"
      - class: "stocking.MissingQuantity"
      - enum: "stocking.Batch"
      - enum: "stocking.QualityAssuredBatch"
      - class: "stocking.LabelledProduct"
  - name: "stocking-outgoing"
    rows:
      - case: "OutgoingEvent.ProductStocked"
      - case: "OutgoingEvent.ProductPalletized"
  - name: "stocking-incoming"
    rows:
      - case: "IncomingEvent.BatchReadyForQualityAssurance"
      - case: "IncomingEvent.ProductRemovedFromStock"
      - case: "IncomingEvent.NewBatch"

  - name: "milk-planning-ul"
    termName: "Term"
    definitionName: "Definition"
    rows:
      - class: "milkplanning.ProcessedMilk"
      - class: "milkplanning.QuintalsOfMilk"
      - class: "milkplanning.Yield"
      - type: "milkplanning.RecipeBook"
      - type: "milkplanning.Stock"
      - class: "milkplanning.StockedQuantity"
      - class: "milkplanning.Quantity"
      - class: "milkplanning.RequestedProduct"
  - name: "milk-planning-incoming"
    termName: "Event"
    definitionName: "Description"
    rows:
      - case: "IncomingEvent.ReceivedOrder"
  - name: "milk-planning-outgoing"
    termName: "Event"
    definitionName: "Description"
    rows:
      - case: "OutgoingEvent.OrderMilk"

  - name: "production-ul"
    rows:
      - class: "production.ProductionPlan"
      - class: "production.ProductionPlanItem"
      - case: "production.Production.ToStart"
        name: "Production To Start"
      - case: "production.Production.InProgress"
        name: "Production In Progress"
      - case: "production.Production.Ended"
        name: "Ended Production"
      - class: "production.RecipeBook"
      - class: "production.Recipe"
      - class: "production.QuintalsOfIngredient"
      - class: "production.CheeseTypeRipeningDays"
      - class: "production.RipeningDays"
  - name: "production-outgoing"
    termName: "Event"
    definitionName: "Description"
    rows:
      - case: "OutgoingEvent.StartProduction"
      - case: "OutgoingEvent.NewBatch"
  - name: "production-incoming"
    termName: "Event"
    definitionName: "Description"
    rows:
      - case: "IncomingEvent.ProductionPlanReady"
      - case: "IncomingEvent.ProductionEnded"

  - name: "restocking-ul"
    rows:
      - type: "restocking.Stock"
      - class: "restocking.StockedMilk"
      - class: "restocking.QuintalsOfIngredient"
      - class: "restocking.QuintalsOfMilk"
  - name: "restocking-incoming"
    termName: "Event"
    definitionName: "Description"
    rows:
      - case: "IncomingEvent.OrderMilk"
      - case: "IncomingEvent.ProductionStarted"

  - name: "production-planning-ul"
    rows:
      - class: "productionplanning.ProductionPlan"
      - class: "productionplanning.ProductToProduce"
      - class: "productionplanning.MissingProducts"
      - class: "productionplanning.Order"
      - class: "productionplanning.OrderedProduct"
      - class: "productionplanning.CheeseTypeRipeningDays"
      - class: "productionplanning.RipeningDays"
  - name: "production-planning-incoming"
    rows:
      - case: "IncomingEvent.NewOrderReceived"
  - name: "production-planning-outgoing"
    rows:
      - case: "OutgoingEvent.ProductionPlanReady"
      - case: "OutgoingEvent.OrderDelayed"

  - name: "client-orders-ul"
    rows:
      - class: "clientorders.IncomingOrder"
      - class: "clientorders.IncomingOrderLine"
      - class: "clientorders.Client"
      - class: "clientorders.Location"
      - class: "clientorders.PricedOrder"
      - class: "clientorders.PricedOrderLine"
      - class: "clientorders.InProgressOrder"
      - enum: "clientorders.InProgressOrderLine"
      - class: "clientorders.CompletedOrder"
      - class: "clientorders.CompleteOrderLine"
      - class: "clientorders.TransportDocument"
      - class: "clientorders.TransportDocumentLine"
  - name: "client-orders-incoming"
    rows:
      - case: "IncomingEvent.OrderReceived"
      - case: "IncomingEvent.ProductPalletizedForOrder"
      - case: "IncomingEvent.OrderCompleted"
  - name: "client-orders-outgoing"
    rows:
      - case: "OutgoingEvent.OrderProcessed"

  - name: "pricing-ul"
    rows:
      - class: "pricing.IncomingOrderLine"
      - class: "pricing.Quantity"
      - class: "pricing.PriceList"
      - class: "pricing.PriceInEuroCents"
      - class: "pricing.Client"
      - class: "pricing.ClientID"
        name: "Client id"
      - class: "pricing.Promotion"
      - case: "pricing.PromotionLine.Fixed"
        name: "Fixed promotion line"
      - case: "pricing.PromotionLine.Threshold"
        name: "Threshold promotion line"
      - class: "pricing.ThresholdQuantity"
      - class: "pricing.DiscountPercentage"

  - name: "shared-kernel-ul"
    rows:
      - enum: "CheeseType"
      - enum: "Product"
      - enum: "Ingredient"
ignored: []
