tables:
  - name: "milk-planning-ul"
    termName: "Term"
    definitionName: "Definition"
    rows:
      - enum: "CheeseType"
      - enum: "Product"
      - class: "ProcessedMilk"
      - class: "QuintalsOfMilk"
      - class: "Period"
      - type: "RecipeBook"
      - type: "Stock"
      - class: "StockedQuantity"
ignored:
  - class: "Week"
  - class: "Year"
  - case: "Squacquerone"
  - case: "Casatella"
  - case: "Ricotta"
  - case: "Stracchino"
  - case: "Caciotta"
  - type: "SquacqueroneSizeInGrams"
  - type: "CasatellaSizeInGrams"
  - type: "RicottaSizeInGrams"
  - type: "StracchinoSizeInGrams"
  - type: "CaciottaSizeInGrams"
  - type: "PositiveNumber"
  - type: "PositiveDecimal"
  - type: "NumberInClosedRange"
  - type: "NonNegativeNumber"