name: Build and publish documentation site

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Build Site
        run: sbt 'unidoc; ubidoc; clean; unidoc'

      - name: Deploy site
        if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/site

